CRB 41
gluwa/sawtooth-legacy-core pull request #2
Opened 2021-06-17 01:22 UTC by CAGS295

networking port including:
- gossip.py
- gossip_handlers.py
- interconnect.py

2021-06-19 14:15 UTC, CAGS295 commented
Included CRB-131

2021-06-23 03:57 UTC, CAGS295 commented
Needs more work. I will continue once 1.7.0 deadlock is fixed.

2021-10-03 00:12 UTC, will-gluwa commented on validator/sawtooth_validator/gossip/gossip.py
> +<< << << < HEAD
@CAGS295 There's merge conflict tags here, which break the build:
> sawtooth-validator | [2021-10-03 00:04:01.635 WARNING  (unknown file)] [src/pylogger.rs: 39] Started logger at level DEBUG
sawtooth-validator | [2021-10-03 00:04:01.813 DEBUG    ffi] loading library libsawtooth_validator.so
sawtooth-validator | [2021-10-03 00:04:01.815 DEBUG    ffi] loading library libsawtooth_validator.so
sawtooth-validator | [2021-10-03 00:04:01.971 ERROR    (unknown file)] failed to load sawtooth_validator.server.cli
sawtooth-validator | Traceback (most recent call last):
sawtooth-validator |   File "/usr/lib/python3/dist-packages/sawtooth_validator/server/cli.py", line 32, in <module>
sawtooth-validator |     from sawtooth_validator.server.core import Validator
sawtooth-validator |   File "/usr/lib/python3/dist-packages/sawtooth_validator/server/core.py", line 61, in <module>
sawtooth-validator |     from sawtooth_validator.gossip.gossip import Gossip
sawtooth-validator |   File "/usr/lib/python3/dist-packages/sawtooth_validator/gossip/gossip.py", line 729
sawtooth-validator |     << << << < HEAD
sawtooth-validator |      ^
sawtooth-validator | SyntaxError: invalid syntax
sawtooth-validator | bash: line 33: EOF: command not found
sawtooth-validator exited with code 127

2021-12-10 18:50 UTC, atodorov approved these changes

2021-12-10 23:19 UTC, seandeneen-gluwa approved these changes

2021-12-14 17:52 UTC, atodorov requested changes
@CAGS295 can you rebase

2021-12-16 11:23 UTC, atodorov approved these changes

2021-12-21 17:38 UTC, merged