[CRB-137] Purge invalid transactions
gluwa/sawtooth-legacy-core pull request #29
Opened 2021-08-10 22:06 UTC by nathanwhit

Split off from #4. Without this change, invalid transactions are continually re-scheduled and end up clogging up the TP.

2021-08-12 11:48 UTC, atodorov commented
Similar comment here, while we're fixing pylint errors I don't see pylint being executed in CI to give us confidence in the changes.

2021-12-01 16:04 UTC, seandeneen-gluwa approved these changes

2021-12-01 16:40 UTC, CAGS295 requested changes
I would split the PR into 3; exception handling, purging transactions, new dict/list refactoring. Out of the three, I would only stay with purging transactions for review. Unless the rest are accepted in the Hyperledger fork, small changes like these are not worth the maintainability cost, IMO.

As far as purging transactions go, I'm not sure how purged invalid transactions will interact with the Creditcoin CLI, can a command return success over purged transactions? If fork resolution happens and batches are displaced, can successful (from the CLI perspective) transactions disappear? When we purge a transaction how do we handle its dependents? Would the node request missing (is the validator aware of purged transactions) transactions? Purge in cascade? Fail and retry? How are clients and other listeners notified that transactions went missing(purged) I think it would take a thorough discussion before we can think of purging transactions.

2021-12-01 18:25 UTC, atodorov approved these changes
LGTM

2022-04-01 19:05 UTC, closed without merging