Fix state verifier for revalidation of state data
gluwa/sawtooth-legacy-core pull request #57
Opened 2022-01-06 19:02 UTC by nathanwhit

This PR fixes the state verifier, which I missed in #50 when renaming arguments. This is necessary for the revalidation upgrade path to work properly in the coming release. This case is triggered when we have a block DB but no state DB, or the state DB is missing data for committed blocks.

2022-01-06 21:14 UTC, seandeneen-gluwa approved these changes

2022-01-07 00:29 UTC, CAGS295 approved these changes

2022-01-07 18:35 UTC, atodorov requested changes
Steps to reproduce:
1) `rm merkle-00.lmdb`, FTR I did `rm merkle-00.lmdb*` which also removed the `.lock` file
2) You'll see a log message "Recomputing missing state from block" and it'll run through the transactions again.

I see 
```
sawtooth-validator.log:2022-01-07T18:25:46.970991852Z [2022-01-07 18:25:46.968 INFO     state_verifier] Recomputing missing state from block a315c1bc2e6851cb68d54eba02bd5abc755ae13f356ecf4a3628e3fc40baa0b037eec57b4febf5bda7fe40fbfe451a5a6ba634aefe0d19aa1589b0074d80ee54 (block_num:0, state:b77a0cbf0c8cbacd5fc66ecedbb8e829f3785526b4087d9d2c7002e8e2f3c0b3, previous_block_id:0000000000000000) with parallel scheduler
```

and then `Verifying state for block` from blocks 1 to 121 afterwards I get a traceback

```
2022-01-07T18:25:49.594890251Z [2022-01-07 18:25:49.593 ERROR    (unknown file)] error executing main
2022-01-07T18:25:49.594929350Z Traceback (most recent call last):
2022-01-07T18:25:49.594936550Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/server/state_verifier.py", line 264, in process_blocks
2022-01-07T18:25:49.594943450Z     state_view_factory.create_view(block.state_root_hash)
2022-01-07T18:25:49.594949850Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/state/state_view.py", line 77, in create_view
2022-01-07T18:25:49.594955650Z     merkle_root=state_root_hash)
2022-01-07T18:25:49.594961050Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/state/merkle.py", line 44, in __init__
2022-01-07T18:25:49.594969050Z     init_root, ctypes.byref(self.pointer))
2022-01-07T18:25:49.594974550Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/state/merkle.py", line 219, in _libexec
2022-01-07T18:25:49.594980350Z     raise KeyError("Value was not found")
2022-01-07T18:25:49.594986050Z KeyError: 'Value was not found'
2022-01-07T18:25:49.594991150Z 
2022-01-07T18:25:49.594995950Z During handling of the above exception, another exception occurred:
2022-01-07T18:25:49.595001050Z 
2022-01-07T18:25:49.595006150Z Traceback (most recent call last):
2022-01-07T18:25:49.595025850Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/server/cli.py", line 260, in main
2022-01-07T18:25:49.595056949Z     validator_config.scheduler)
2022-01-07T18:25:49.595060849Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/server/state_verifier.py", line 208, in verify_state
2022-01-07T18:25:49.595064549Z     state_view_factory=state_view_factory)
2022-01-07T18:25:49.595068049Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/server/state_verifier.py", line 275, in process_blocks
2022-01-07T18:25:49.595071649Z     previous_block_id=block.previous_block_id)
2022-01-07T18:25:49.595075149Z   File "/usr/lib/python3/dist-packages/sawtooth_validator/server/state_verifier.py", line 316, in execute_batches
2022-01-07T18:25:49.595078749Z     "Batch {} was invalid".format(batch_id))
2022-01-07T18:25:49.595082449Z sawtooth_validator.server.state_verifier.ExecutionError: Batch 59086ded268658d49c895262fe37d3f001c1490401a9f4a14df052c62e4fe0054da92244f3209744a7f61701afc184ab69671654f321ea21d8c05d1a8daec702 was invalid
```

this includes PRs https://github.com/gluwa/Creditcoin-Processor-Rust/pull/51, https://github.com/gluwa/Creditcoin-Processor-Rust/pull/52, https://github.com/gluwa/Creditcoin-Processor-Rust/pull/53 and https://github.com/gluwa/Creditcoin-Processor-Rust/pull/54

2022-01-07 19:14 UTC, atodorov approved these changes
Including the changes in https://github.com/gluwa/Sawtooth-Core/pull/58 there's no crash and I see multiple messages like this:

```
[2022-01-07 19:14:31.598 INFO     state_verifier] Verifying state for block e19b98e8eca3ce8a9fb143bdd2bd2f207ac910e1daa1c844e48938029325ecde7554b10b21f0eb2d6239bb9bf8ac2ac3d0cd9090e28eb0ca675b7a7e403a90ea (block_num:2030, state:b5dfd38eb6efcbb1bdca76fde6ec2ed33c6d4d20c34d30fbeed837cb089d57e1, previous_block_id:43ac9e24b795e709739c7d84908606de8dc7b46e47ec139a4e352451986d97c77c033ebe3f9703e4804b924a950ef6a7430a26bc701d0594082e40b4e9a84db3)
```

block_num keeps rising up. This is with the production snapshot data.

2022-01-11 09:49 UTC, merged