CRB-301 exit if min_peers is not sustained
gluwa/sawtooth-legacy-core pull request #60
Opened 2022-01-12 03:55 UTC by CAGS295

Go to the ticket for a description.

2022-01-12 10:23 UTC, atodorov requested changes

2022-01-12 10:23 UTC, atodorov commented on validator/sawtooth_validator/server/core.py
> +        ...
`...` isn't valid Python. This will lead to SyntaxError. Use `pass`.

2022-01-12 14:57 UTC, atodorov requested changes
Doesn't make things better. See ticket for more info and logs.

2022-01-12 17:23 UTC, nathanwhit commented
This will trigger a graceful exit, but in my experience a graceful exit is not guaranteed to actually terminate, depending on the state of zeroMQ sockets. The disconnect messages are sent immediately when a graceful exit is triggered, so forcefully exiting after a bit should be okay. You could maybe try a timer or something in the exit logic that forces an exit if the graceful exit doesn't complete in X seconds.

2022-01-12 18:50 UTC, nathanwhit commented
@atodorov Pushed a new commit, give it a try and let me know how it goes

2022-01-12 20:02 UTC, atodorov approved these changes
@nathanwhit , @CAGS295 

```
[2022-01-12 19:52:58.037 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.037 ERROR    cli] 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sawtooth_validator/server/cli.py", line 299, in main
    validator.start()
  File "/usr/lib/python3/dist-packages/sawtooth_validator/server/core.py", line 454, in start
    self._start()
  File "/usr/lib/python3/dist-packages/sawtooth_validator/server/core.py", line 481, in _start
    raise self.RebootException()
sawtooth_validator.server.core.Validator.RebootException
[2022-01-12 19:52:58.039 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.041 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.042 ERROR    proxy] Settings from block b62f9590e71049c971ebadd42cd9eb4ca477fa8f2b2360c30d5268720a04f1f203ac773ebdcc8cd4b2ae6b83b638ee060b3318a8b1b36f6d46ebc4b0ed7b944c requested, but root hash 2284aaab059f6094f2ac913511eceb7d084ed3bc2e9fdcaa48248fb7cb5cc733 was missing. Returning no setting values.
[2022-01-12 19:52:58.043 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.044 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.045 DEBUG    dispatch] Removed send_message function for connection ServerThread
[2022-01-12 19:52:58.046 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.047 DEBUG    dispatch] Removed send_last_message function for connection ServerThread
[2022-01-12 19:52:58.050 DEBUG    ffi] [src/journal/block_scheduler.rs: 119] During block scheduling, previous block b62f9590e71049c971ebadd42cd9eb4ca477fa8f2b2360c30d5268720a04f1f203ac773ebdcc8cd4b2ae6b83b638ee060b3318a8b1b36f6d46ebc4b0ed7b944c is pending, adding block 0c1484c2891e7b5ed68aa54a3bad9db23309d6f8dcf8b3d51a752017463151036693e1c9915d2d084ee5a8df4dcd1b45102bbdbd56347cca27c401ebd42f201c to pending
[2022-01-12 19:52:58.051 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.051 DEBUG    dispatch] Removed send_message function for connection OutboundConnectionThread-tcp://20.188.27.55:8800
[2022-01-12 19:52:58.053 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.053 DEBUG    dispatch] Removed send_last_message function for connection OutboundConnectionThread-tcp://20.188.27.55:8800
[2022-01-12 19:52:58.054 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.054 DEBUG    dispatch] Removed send_message function for connection OutboundConnectionThread-tcp://40.112.252.222:8800
[2022-01-12 19:52:58.055 ERROR    proxy] Settings from block 0c1484c2891e7b5ed68aa54a3bad9db23309d6f8dcf8b3d51a752017463151036693e1c9915d2d084ee5a8df4dcd1b45102bbdbd56347cca27c401ebd42f201c requested, but root hash 2284aaab059f6094f2ac913511eceb7d084ed3bc2e9fdcaa48248fb7cb5cc733 was missing. Returning no setting values.
[2022-01-12 19:52:58.057 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.057 DEBUG    dispatch] Removed send_last_message function for connection OutboundConnectionThread-tcp://40.112.252.222:8800
[2022-01-12 19:52:58.058 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.058 DEBUG    dispatch] Removed send_message function for connection OutboundConnectionThread-tcp://54.185.193.31:8800
[2022-01-12 19:52:58.059 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.060 DEBUG    dispatch] Removed send_last_message function for connection OutboundConnectionThread-tcp://54.185.193.31:8800
[2022-01-12 19:52:58.061 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.067 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.067 DEBUG    ffi] [src/journal/block_scheduler.rs: 119] During block scheduling, previous block 0c1484c2891e7b5ed68aa54a3bad9db23309d6f8dcf8b3d51a752017463151036693e1c9915d2d084ee5a8df4dcd1b45102bbdbd56347cca27c401ebd42f201c is pending, adding block 4f88a6ebcc10b88365bf01d0ff17e63e08577d284278e7e57e5a25a43e5ecdd93b0436d2240196b674041c0cd4c0819d24a38dc28968eaaa77d09c4ccb383f23 to pending
[2022-01-12 19:52:58.068 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.069 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.070 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidationError("During validate_on_chain_rules, error creating settings view: NotFound(\"ff686b84cf07d9923bd5b7f1d6f2426a26b969a5d756ba189615dbc287211cb3\")")
[2022-01-12 19:52:58.071 WARNING  (unknown file)] [src/journal/block_validator.rs: 293] Error during block validation: BlockValidatio [...]

2022-01-12 21:25 UTC, nathanwhit commented
@atodorov Added another commit. Before we were blocking to wait on thread pools before exiting, now if we're rebooting we won't block.

2022-01-14 16:21 UTC, seandeneen-gluwa approved these changes

2022-01-14 16:55 UTC, merged